In [1]:
# import cv2
import cv2

### Image representatiom

In [22]:
# load image
img=cv2.imread("Assets/la_eterna_14.jpg")
# load image
img=cv2.imread("Assets/la_eterna_14.jpg")

In [4]:
print(type(img))

<class 'numpy.ndarray'>


In [5]:
print(img.shape)

(224, 224, 3)


In [ ]:
## NOTE:
### IMAGES are represented in arrays inside another arrays
### e.g [
###    [],
###    [], these three arrays represent the rows of the image
###    [],
###]
### Assuming we have two pixels by two pixels
### [
###   [[0,0,0],[255,255,255]], Where each pixel is represented in blue,green,red
###   [[0,0,0],[255,255,255]]
###]




In [13]:
# Manually manipulating images
# print first row of image
print(img[220])
# check certain pixel value
print(img[0][2:5])


[[ 65 169 114]
 [ 49 157 104]
 [ 31 145  92]
 [  2 117  68]
 [  1 111  69]
 [  1 108  69]
 [ 10 110  74]
 [ 13 109  73]
 [ 16 106  71]
 [  8  95  59]
 [ 13  97  62]
 [ 15  99  64]
 [ 12  96  62]
 [ 16 100  71]
 [ 12  96  68]
 [ 14 103  77]
 [ 12 116  91]
 [ 23 139 110]
 [ 22 146 110]
 [ 16 148 107]
 [ 13 151 109]
 [  3 147 105]
 [  1 143 106]
 [ 15 151 117]
 [ 46 167 133]
 [ 59 172 138]
 [ 59 172 134]
 [ 55 168 130]
 [ 42 154 124]
 [ 25 151 129]
 [ 26 177 162]
 [ 43 211 204]
 [ 34 210 210]
 [ 22 204 204]
 [ 28 211 207]
 [ 15 191 184]
 [ 22 187 174]
 [ 16 168 149]
 [ 24 162 138]
 [ 39 165 136]
 [ 56 168 134]
 [ 68 169 131]
 [ 74 166 123]
 [ 77 165 119]
 [ 73 159 111]
 [ 71 152 103]
 [ 74 149  98]
 [ 73 143  96]
 [ 66 136  95]
 [ 60 133  93]
 [ 59 135  93]
 [ 51 133  90]
 [ 43 132  88]
 [ 36 134  88]
 [ 32 135  90]
 [ 33 139  98]
 [ 34 143 104]
 [ 33 146 109]
 [ 35 148 114]
 [ 33 149 114]
 [ 29 145 110]
 [ 25 141 106]
 [ 20 136 101]
 [ 16 132  97]
 [ 20 136 101]
 [ 20 135 102]
 [ 19 133 

In [14]:

# check certain pixel value
print(img[0][2:5])


[[ 84 173 134]
 [ 86 169 131]
 [ 74 154 117]]


In [16]:
# check a pixel value
print(img[0][2])

[ 84 173 134]


In [21]:
# changing pixels value
import random
for i in range(100):
    for j in range(img.shape[1]):
        img[i][j]=[random.randint(0,255),random.randint(0,255),random.randint(0,255)]
cv2.imshow("image",img)
cv2.waitKey(0)
cv2.destroyAllWindows()
# The top of the image becomes random color because the pixels values are randomly selected

In [ ]:
#### copying one part of an image and pasting it in another
tag=img2[10:150,50:170]
img2[20:160,40:160]=tag
cv2.imshow("image",img2)
cv2.waitKey(0)
cv2.destroyAllWindows()
